/* Auto-generated by gen-acts-registry.lua - do not edit. */
#ifndef ACTS_GEN_H
#define ACTS_GEN_H

#include <stdbool.h>
#include <stddef.h>

#define MAX_ACT_WIDTH  2880
#define MAX_ACT_HEIGHT 1344
#define MAX_ROOM_HEIGHT 694
#define ACT_COUNT      2
#define MAX_ROOMS_PER_ACT 16
#define MAX_TUNNELS_PER_ACT 16
#define MAX_TELEPORTS_PER_ACT 16
#define MAX_SAVES_PER_ACT 16

typedef struct SavePointDef {
    int index;
    float x, y;
    const char *room_id;
} SavePointDef;

typedef struct RoomDef {
    const char *id;
    const char *name;
    bool isolated;
    float x, y, w, h;
    float view_y, view_h;
} RoomDef;

typedef struct TunnelDef {
    const char *id;
    const char *room_a_id;
    const char *room_b_id;
    float x, y, w, h;
    float spawn_ax, spawn_ay;
    float spawn_bx, spawn_by;
} TunnelDef;

typedef struct TeleportDef {
    const char *id;
    const char *room_id;
    const char *link_id;
    const char *name;
    float x, y, w, h;
    float spawn_x, spawn_y;
} TeleportDef;

typedef struct ActDef {
    const char *id;
    const char *label;
    int width;
    int height;
    int cols;
    int rows;
    const char *background_png;
    const char *collision_png;
    const SavePointDef *saves;
    int save_count;
    const RoomDef *rooms;
    int room_count;
    const TunnelDef *tunnels;
    int tunnel_count;
    const TeleportDef *teleports;
    int teleport_count;
} ActDef;

static const SavePointDef ACT_green_act_SAVES[1] = {
    { .index = 0, .x = 30.0f, .y = 335.0f, .room_id = "r-1" }
};

static const RoomDef ACT_green_act_ROOMS[3] = {
    { .id = "ir-1", .name = "Isolated Room 1", .isolated = true, .x = 0.0f, .y = 512.0f, .w = 288.0f, .h = 241.0f, .view_y = 512.0f, .view_h = 241.0f },
    { .id = "ir-2", .name = "Isolated Room 2", .isolated = true, .x = 0.0f, .y = 783.0f, .w = 288.0f, .h = 225.0f, .view_y = 783.0f, .view_h = 225.0f },
    { .id = "r-1", .name = "Act Start", .isolated = false, .x = -1.0f, .y = 176.0f, .w = 199.0f, .h = 208.0f, .view_y = 176.0f, .view_h = 208.0f }
};

static const TunnelDef ACT_green_act_TUNNELS[0] = {
};

static const TeleportDef ACT_green_act_TELEPORTS[5] = {
    { .id = "teleport-ir1-a", .room_id = "ir-1", .link_id = "teleport-r1-a", .name = "Teleport to Start", .x = 15.0f, .y = 720.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 23.0f, .spawn_y = 728.0f },
    { .id = "teleport-ir1-b", .room_id = "ir-1", .link_id = "teleport-ir2-a", .name = "Teleport to Isolated Room 2", .x = 256.0f, .y = 720.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 264.0f, .spawn_y = 728.0f },
    { .id = "teleport-ir2-a", .room_id = "ir-2", .link_id = "teleport-ir1-b", .name = "Teleport to Isolated Room 1", .x = 15.0f, .y = 848.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 23.0f, .spawn_y = 856.0f },
    { .id = "teleport-ir2-b", .room_id = "ir-2", .link_id = "teleport-r1-a", .name = "Teleport to Start", .x = 256.0f, .y = 832.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 264.0f, .spawn_y = 840.0f },
    { .id = "teleport-r1-a", .room_id = "r-1", .link_id = "teleport-ir1-a", .name = "Teleport to Isolated Room 1", .x = 16.0f, .y = 272.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 24.0f, .spawn_y = 280.0f }
};

static const SavePointDef ACT_dark_act_SAVES[6] = {
    { .index = 0, .x = 147.0f, .y = 315.0f, .room_id = "r-1" },
    { .index = 1, .x = 1159.0f, .y = 197.0f, .room_id = "r-2" },
    { .index = 2, .x = 2120.0f, .y = 88.0f, .room_id = "r-3" },
    { .index = 3, .x = 2304.0f, .y = 953.0f, .room_id = "r-7" },
    { .index = 4, .x = 1737.0f, .y = 630.0f, .room_id = "r-8" },
    { .index = 6, .x = 616.0f, .y = 471.0f, .room_id = "r-9" }
};

static const RoomDef ACT_dark_act_ROOMS[11] = {
    { .id = "ir-1", .name = "Isolated Room 1", .isolated = true, .x = 32.0f, .y = 528.0f, .w = 288.0f, .h = 241.0f, .view_y = 528.0f, .view_h = 241.0f },
    { .id = "ir-2", .name = "Isolated Room 2", .isolated = true, .x = 32.0f, .y = 799.0f, .w = 288.0f, .h = 225.0f, .view_y = 799.0f, .view_h = 225.0f },
    { .id = "r-1", .name = "Act Start", .isolated = false, .x = 29.0f, .y = 183.0f, .w = 787.0f, .h = 218.0f, .view_y = 183.0f, .view_h = 218.0f },
    { .id = "r-2", .name = NULL, .isolated = false, .x = 959.0f, .y = 127.0f, .w = 623.0f, .h = 274.0f, .view_y = 127.0f, .view_h = 274.0f },
    { .id = "r-3", .name = NULL, .isolated = false, .x = 1697.0f, .y = 12.0f, .w = 614.0f, .h = 324.0f, .view_y = 12.0f, .view_h = 324.0f },
    { .id = "r-4", .name = NULL, .isolated = false, .x = 2545.0f, .y = 131.0f, .w = 160.0f, .h = 336.0f, .view_y = 131.0f, .view_h = 336.0f },
    { .id = "r-5", .name = NULL, .isolated = false, .x = 2240.0f, .y = 397.0f, .w = 160.0f, .h = 337.0f, .view_y = 397.0f, .view_h = 337.0f },
    { .id = "r-6", .name = NULL, .isolated = false, .x = 2560.0f, .y = 655.0f, .w = 151.0f, .h = 404.0f, .view_y = 655.0f, .view_h = 404.0f },
    { .id = "r-7", .name = NULL, .isolated = false, .x = 2238.0f, .y = 927.0f, .w = 160.0f, .h = 274.0f, .view_y = 927.0f, .view_h = 274.0f },
    { .id = "r-8", .name = NULL, .isolated = false, .x = 1216.0f, .y = 512.0f, .w = 691.0f, .h = 694.0f, .view_y = 512.0f, .view_h = 694.0f },
    { .id = "r-9", .name = NULL, .isolated = false, .x = 430.0f, .y = 431.0f, .w = 713.0f, .h = 610.0f, .view_y = 431.0f, .view_h = 610.0f }
};

static const TunnelDef ACT_dark_act_TUNNELS[8] = {
    { .id = "door-1", .room_a_id = "r-1", .room_b_id = "r-2", .x = 783.0f, .y = 208.0f, .w = 193.0f, .h = 32.0f, .spawn_ax = 799.5f, .spawn_ay = 232.0f, .spawn_bx = 967.5f, .spawn_by = 232.0f },
    { .id = "door-2", .room_a_id = "r-2", .room_b_id = "r-3", .x = 1564.0f, .y = 161.0f, .w = 148.0f, .h = 31.0f, .spawn_ax = 1573.0f, .spawn_ay = 184.0f, .spawn_bx = 1704.5f, .spawn_by = 184.0f },
    { .id = "door-3", .room_a_id = "r-3", .room_b_id = "r-4", .x = 2288.0f, .y = 144.0f, .w = 276.0f, .h = 32.0f, .spawn_ax = 2299.5f, .spawn_ay = 168.0f, .spawn_bx = 2554.5f, .spawn_by = 168.0f },
    { .id = "door-4", .room_a_id = "r-4", .room_b_id = "r-5", .x = 2382.0f, .y = 416.0f, .w = 180.0f, .h = 32.0f, .spawn_ax = 2553.5f, .spawn_ay = 440.0f, .spawn_bx = 2391.0f, .spawn_by = 440.0f },
    { .id = "door-6", .room_a_id = "r-5", .room_b_id = "r-6", .x = 2382.0f, .y = 672.0f, .w = 198.0f, .h = 32.0f, .spawn_ax = 2391.0f, .spawn_ay = 696.0f, .spawn_bx = 2570.0f, .spawn_by = 696.0f },
    { .id = "door-7", .room_a_id = "r-6", .room_b_id = "r-7", .x = 2382.0f, .y = 988.0f, .w = 196.0f, .h = 38.0f, .spawn_ax = 2569.0f, .spawn_ay = 1018.0f, .spawn_bx = 2390.0f, .spawn_by = 1018.0f },
    { .id = "door-8", .room_a_id = "r-7", .room_b_id = "r-8", .x = 1872.0f, .y = 1120.0f, .w = 384.0f, .h = 33.0f, .spawn_ax = 2247.0f, .spawn_ay = 1145.0f, .spawn_bx = 1889.5f, .spawn_by = 1145.0f },
    { .id = "door-9", .room_a_id = "r-8", .room_b_id = "r-9", .x = 1088.0f, .y = 544.0f, .w = 160.0f, .h = 48.0f, .spawn_ax = 1232.0f, .spawn_ay = 584.0f, .spawn_bx = 1115.5f, .spawn_by = 584.0f }
};

static const TeleportDef ACT_dark_act_TELEPORTS[5] = {
    { .id = "teleport-ir1-a", .room_id = "ir-1", .link_id = "teleport-r1-a", .name = "Teleport to Start", .x = 47.0f, .y = 736.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 55.0f, .spawn_y = 744.0f },
    { .id = "teleport-ir1-b", .room_id = "ir-1", .link_id = "teleport-ir2-a", .name = "Teleport to Isolated Room 2", .x = 288.0f, .y = 736.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 296.0f, .spawn_y = 744.0f },
    { .id = "teleport-ir2-a", .room_id = "ir-2", .link_id = "teleport-ir1-b", .name = "Teleport to Isolated Room 1", .x = 47.0f, .y = 864.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 55.0f, .spawn_y = 872.0f },
    { .id = "teleport-ir2-b", .room_id = "ir-2", .link_id = "teleport-r1-a", .name = "Teleport to Start", .x = 288.0f, .y = 848.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 296.0f, .spawn_y = 856.0f },
    { .id = "teleport-r1-a", .room_id = "r-1", .link_id = "teleport-ir1-a", .name = "Teleport to Isolated Room 1", .x = 48.0f, .y = 288.0f, .w = 16.0f, .h = 16.0f, .spawn_x = 56.0f, .spawn_y = 296.0f }
};

static const ActDef ACTS[ACT_COUNT] = {
    {
        .id = "green-act",
        .label = "Green Act",
        .width = 2208, .height = 1008,
        .cols = 138, .rows = 63,
        .background_png = "resources/visual/layers/green-act-background.png",
        .collision_png = "resources/visual/layers/green-act.png",
        .saves = ACT_green_act_SAVES,
        .save_count = 1,
        .rooms = ACT_green_act_ROOMS,
        .room_count = 3,
        .tunnels = ACT_green_act_TUNNELS,
        .tunnel_count = 0,
        .teleports = ACT_green_act_TELEPORTS,
        .teleport_count = 5,
    },
    {
        .id = "dark-act",
        .label = "Dark Act",
        .width = 2880, .height = 1344,
        .cols = 180, .rows = 84,
        .background_png = "resources/visual/layers/dark-act-background.png",
        .collision_png = "resources/visual/layers/dark-act.png",
        .saves = ACT_dark_act_SAVES,
        .save_count = 6,
        .rooms = ACT_dark_act_ROOMS,
        .room_count = 11,
        .tunnels = ACT_dark_act_TUNNELS,
        .tunnel_count = 8,
        .teleports = ACT_dark_act_TELEPORTS,
        .teleport_count = 5,
    }
};

#endif
